# Generated by Django 5.2.4 on 2025-07-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='url_libro',
        ),
        migrations.AddField(
            model_name='libro',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='libro',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
